worker_processes auto;
error_log /dev/stderr;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;

    types {
        text/html                             html htm shtml;
        text/css                              css;
        text/javascript                       js mjs;
        application/javascript                js mjs;
        application/json                      json;
        image/png                             png;
        image/jpeg                            jpeg jpg;
        image/gif                             gif;
        image/svg+xml                         svg svgz;
        image/x-icon                          ico;
        image/webp                            webp;
        font/woff                             woff;
        font/woff2                            woff2;
        application/font-woff                 woff;
        application/font-woff2                woff2;
    }

    server {
        listen 80;
        server_name _;

        root /app/static;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        location /yt {
            return 301 https://www.youtube.com/@AlgoraKiko;
        }

        location /youtube {
            return 301 https://www.youtube.com/@AlgoraKiko;
        }

        location /t {
            return 301 https://twitter.com/AlgoraKiko;
        }

        location /x {
            return 301 https://twitter.com/AlgoraKiko;
        }

        location /twt {
            return 301 https://twitter.com/AlgoraKiko;
        }

        location /twitter {
            return 301 https://twitter.com/AlgoraKiko;
        }

        location /ttv {
            return 301 https://twitch.tv/AlgoraKiko;
        }

        location /twitch {
            return 301 https://twitch.tv/AlgoraKiko;
        }

        location /discord {
            return 301 https://discord.com/invite/cFVFG26;
        }

        location /insta {
            return 301 https://www.instagram.com/algorakiko/;
        }

        location /instagram {
            return 301 https://www.instagram.com/algorakiko/;
        }

        location /tiktok {
            return 301 https://www.tiktok.com/@algorakiko;
        }

        location /spotify {
            return 301 https://open.spotify.com/user/jailenetalampas;
        }

        location /static/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
